// Narrative conclusions for the account-manager email — generated by Claude, grounded strictly in
// the period's report data (no invented numbers). Raw fetch to the Anthropic Messages API.
import type { ManagerReport } from "./managerReport";
import type { Channel } from "./types";

const MODEL = process.env.ANTHROPIC_MODEL ?? "claude-sonnet-5";
export function conclusionsConfigured(): boolean {
  return Boolean(process.env.ANTHROPIC_API_KEY);
}

const pct = (cur: number | null, prev: number | null) => (cur == null || prev == null || prev === 0 ? null : Math.round(((cur - prev) / prev) * 100));

export async function generateConclusions(r: ManagerReport): Promise<string[]> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return [];
  const m = r.metrics;
  const p = m?.previous ?? null;

  const data = {
    brand: r.brandName,
    period: r.period === "week" ? "שבוע" : "חודש",
    range: `${r.from} → ${r.to}`,
    kpis: m
      ? {
          spend: Math.round(m.total.spend),
          storeRevenue: Math.round(m.channels.site.revenue),
          blendedRoas: m.blendedRoas,
          orders: Math.round(m.channels.site.purchases),
          adRoas: m.total.roas,
          cac: m.cac == null ? null : Math.round(m.cac),
          aov: m.channels.site.aov == null ? null : Math.round(m.channels.site.aov),
          newVsReturning: { newRevenue: Math.round(m.newRevenue), returningRevenue: Math.round(m.returningRevenue) },
          deltasPctVsPrev: p ? { spend: pct(m.total.spend, p.spend), storeRevenue: pct(m.channels.site.revenue, p.siteRevenue), blendedRoas: pct(m.blendedRoas, p.blendedRoas), orders: pct(m.channels.site.purchases, p.siteOrders) } : null,
        }
      : null,
    channels: m ? (["google", "meta", "tiktok"] as Channel[]).map((ch) => ({ channel: ch, spend: Math.round(m.channels[ch].spend), roas: m.channels[ch].roas })) : [],
    topCreatives: r.topAds.map((a) => ({ name: a.name, spend: a.spend, ctrPct: a.ctr == null ? null : Math.round(a.ctr * 1000) / 10 })),
    promos: r.promos.map((pr) => ({ code: pr.code, orders: pr.orders, revenue: pr.revenue })),
  };

  const system = [
    "אתה אנליסט מדיה בכיר ב-Leaders. כתוב 3–5 מסקנות קצרות, קונקרטיות ומדויקות בעברית עבור מנהלת הלקוח,",
    "בהתבסס אך ורק על הנתונים שסופקו — אל תמציא מספרים או עובדות. התמקד בתחום האחריות שלה:",
    "ביצועים ומגמות מול התקופה הקודמת, קריאייטיבים (מודעות מובילות/חלשות), מבצעים וקודי הנחה, והמלצות/יוזמות קונקרטיות לפעולה מול הלקוח.",
    "כל מסקנה = משפט אחד חד ופרקטי. אם אין מבצעים או קריאייטיבים בנתונים — אל תמציא, דלג.",
    'החזר JSON בלבד בפורמט: {"bullets": ["...", "..."]}',
  ].join(" ");

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "x-api-key": apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify({ model: MODEL, max_tokens: 700, system, messages: [{ role: "user", content: JSON.stringify(data) }] }),
    });
    if (!res.ok) return [];
    const j = (await res.json()) as { content?: Array<{ text?: string }> };
    const text = (j.content?.[0]?.text ?? "").trim();
    const s = text.indexOf("{");
    const e = text.lastIndexOf("}");
    if (s < 0 || e < 0) return [];
    const parsed = JSON.parse(text.slice(s, e + 1)) as { bullets?: unknown };
    return Array.isArray(parsed.bullets) ? parsed.bullets.map(String).filter(Boolean).slice(0, 6) : [];
  } catch {
    return [];
  }
}
