// The written rationale that accompanies a media plan — generated by Claude, grounded strictly
// in the plan's own numbers (same contract as conclusions.ts: no invented figures). If the API
// key is absent or the call fails, the builder's deterministic bullets stand on their own.
import type { MediaPlanDraft } from "./mediaPlanBuilder";
import { KPI_LABEL } from "./mediaPlanRules";

const MODEL = process.env.ANTHROPIC_MODEL ?? "claude-sonnet-5";

export function narrativeConfigured(): boolean {
  return Boolean(process.env.ANTHROPIC_API_KEY);
}

const PROFILE_HE: Record<string, string> = {
  ecommerce: "איקומרס (ROAS)",
  views: "צפיות וחשיפה",
  leads: "לידים",
  app: "התקנות אפליקציה",
  impshare: "נתח חשיפות",
};

export async function generatePlanRationale(d: MediaPlanDraft): Promise<string[]> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return [];

  const data = {
    brand: d.brandName,
    month: d.month,
    clientType: PROFILE_HE[d.profile] ?? d.profile,
    kpi: KPI_LABEL[d.scale.kpi],
    kpiValue: d.scale.kpiValue,
    kpiTarget: d.scale.kpiTarget,
    performanceIndex: d.scale.index,
    budget: {
      source: d.budgetSource === "fixed" ? "תקציב קבוע שנקבע מול הלקוח" : "תקציב מוצע לפי ביצועים",
      planned: d.totalBudget,
      lastMonthActual: d.baselineBudget,
      recommended: d.recommendedBudget,
      scaleFactor: d.scale.factor,
    },
    lookback: { from: d.basis.from, to: d.basis.to, days: d.basis.lookbackDays },
    lines: d.lines.map((l) => ({
      channel: l.channelLabel,
      stage: l.stageLabel,
      budget: l.budget,
      sharePct: l.sharePct,
      lastMonthSpend: l.prevSpend,
      changePct: l.deltaPct,
      forecast: {
        impressions: l.forecast.impressions,
        clicks: l.forecast.clicks,
        purchases: l.forecast.purchases,
        revenue: l.forecast.revenue,
        roas: l.forecast.roas,
        views: l.forecast.views,
        completedViews: l.forecast.completedViews,
        viewRatePct: l.forecast.viewRate == null ? null : Math.round(l.forecast.viewRate * 1000) / 10,
        completionRatePct: l.forecast.completionRate == null ? null : Math.round(l.forecast.completionRate * 100),
        leads: l.forecast.leads,
        installs: l.forecast.installs,
      },
    })),
  };

  const system = [
    "אתה מנהל מדיה בכיר ב-Leaders. כתוב את הרציונל לפריסת המדיה החודשית, למנהלת הלקוח.",
    "כל שורה = משפט אחד, עם מספרים מהדאטה בלבד. אסור להמציא מספרים, ערוצים או עובדות.",
    "",
    "מבנה קבוע, בסדר הזה:",
    "1. התקציב: הסכום המתוכנן, מקורו (קבוע / מוצע), והשינוי מול ההוצאה בפועל בחודש הקודם.",
    "2. הנימוק לסקייל: ה-KPI בפועל מול היעד, ולמה התקציב עולה / יורד / נשאר.",
    "3. ההקצאה המרכזית: הערוץ והשלב בפאנל שמקבלים את החלק הגדול, עם הסכום והאחוז.",
    "4. שינוי בולט אחד: ערוץ/שלב שגדל או קטן משמעותית, עם המספרים לפני ואחרי והסיבה.",
    "5. התחזית: מה הפריסה צפויה להביא (הכנסות/ROAS לאיקומרס, צפיות 15 שניות ללקוח צפיות, לידים ללידים, התקנות לאפליקציה).",
    "   ללקוח צפיות: הצפיות הן צפיות מוכשרות (15 שניות / ThruPlay). לציין גם את שיעור הצפייה ואת אחוז הצפייה המלאה — צפייה זולה שאף אחד לא מסיים אינה תוצאה.",
    "",
    "חוקים: רק מספרים מהדאטה, תמיד לצטט אותם (₪ / % / KPI). אם אין נתון לסעיף — דלג עליו לגמרי.",
    "כל שורה עד 20 מילים, ישיר, בגוף פעיל, בלי עצות גנריות. עברית מקצועית.",
    'החזר JSON בלבד: {"bullets": ["...", "..."]}',
  ].join("\n");

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "x-api-key": apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify({ model: MODEL, max_tokens: 800, system, messages: [{ role: "user", content: JSON.stringify(data) }] }),
    });
    if (!res.ok) return [];
    const j = (await res.json()) as { content?: Array<{ text?: string }> };
    const text = (j.content?.[0]?.text ?? "").trim();
    const s = text.indexOf("{");
    const e = text.lastIndexOf("}");
    if (s < 0 || e < 0) return [];
    const parsed = JSON.parse(text.slice(s, e + 1)) as { bullets?: unknown };
    return Array.isArray(parsed.bullets) ? parsed.bullets.map(String).filter(Boolean).slice(0, 6) : [];
  } catch {
    return [];
  }
}
